### PR TITLE
Convert `Cart` component to hooks to get feedback

### PR DESCRIPTION
**Pull request by Jared-Dev**
I'm been using hooks a bit and wanted to convert a component (in this case `Cart`) and see if this is something you would be interested in happening everywhere that wouldn't require an excessive amount of work.

@jlengstorf or @m-allanson if either of you gets a chance (or anyone else on the core team) let me know the likelihood here and I can see about making some more headway.

### CODE REVIEW

**Comment by Jared-Dev** [comment]
All components in the `Cart` folder have been converted. If this is appealing I'll go ahead and work on others as I have time.

**Comment by m-allanson** [comment]
Thanks @Jared-Dev! I don't think we have an 'official' policy here, but the React docs cover something like it in the [hooks FAQ](https://reactjs.org/docs/hooks-faq.html#do-i-need-to-rewrite-all-my-class-components).

> **Do I need to rewrite all my class components?**
>
> No. There are no plans to remove classes from React — we all need to keep shipping products and can’t afford rewrites. We recommend trying Hooks in new code.

So, where we have _code that works_ we can't prioritise replacing it with _different code that works the same_, unless that change is a setup for future improvements like new functionality or better tests.

That said, this looks like a nice update, thank you! :tada: cc @gatsbyjs/ecosystem does anyone have availability to review this?

**Comment by Jared-Dev** [comment]
@m-allanson gotcha! I was mainly doing this as an exercise in learning how to redo what I already know how to do in a class component!

**Comment by m-allanson** [comment]
Good stuff! That seems like the perfect way to get a handle on how hooks work. I haven't had the chance to properly dig into them yet, so I'm a bit envious :)

**Comment by jlengstorf** [comment]
Sorry for sleeping on this PR. I love the direction here. If you want to pull the latest changes into this branch we should be able to get it properly reviewed and merged.

**Comment by Jared-Dev** [comment]
Sounds good, I've been ramping up with a new position, but will look at doing this once I can!

**Comment by sidharthachatterjee** [comment]
@Jared-Dev Apologies for letting this sit for so long! This appears to be a little stale and we're currently in the process of moving this project over to the monorepo. 

I hope it's alright if I close this for now. 🙂 We'd love to receive a fresh PR from you on the monorepo (once this is moved over of course) updated to the latest code here. 

Please do know that we value your contributions and thank you once again for taking the time to clean this up. See you around 💜

**Pull request closed without merging**
