### PR TITLE
Improve site metadata

### PR DESCRIPTION
**Pull request by cometkim**
- [x] Extract Helmet code as a separated component from Layout
- [x] Add OpenGraph (#134)
- [x] Add TwitterCard
- [x] Add Canonical URL
- [x] Add Description
- [ ] Add image

### CODE REVIEW

**Comment by cometkim** [comment]
@mikelax If you have representative image URL, title, and description to use in site metadata, let me know!

**Comment by scottmathson** [comment]
Adding images would be awesome, Twitter card validation (_and all store.gatsbyjs.org links shared on Twitter_) showing this:

Gatsby Store Twitter card validator

There is no image data/src we could dynamically grab for these, from what I see, right?

`<meta name="twitter:image" content={image} />`

---

Also, what about also adding this into this `SiteMetadata.js` work?

```
<meta name="twitter:creator" content="@gatsbyjs" />
<meta name="twitter:title" content={title} />
<meta name="twitter:description" content={description} />
```

**Comment by scottmathson** [comment]
Would be interested in checking out other optimizations in here, SEO-wise. Adding Schema.org JSON markup, etc.

**Comment by mikelax** [comment]
Here is a basic set of meta tags that one would implement to support cards, etc for most major sites. 

if we are going to add this many additional fields, a possible refactor here would be to create a new file, something like `helmetConfig.js` that contains an exported object of all the tags with values we want. 

```js
export default {
  head: {
    titleTemplate: 'Gatsby Store: %s',
    defaultTitle: 'Gatsby Store',
    meta: [ { property: 'og:type', content: 'website' }, ... ],
    link: [ ... ]
  }
}
```

Then in a `layout.js` you can have a simple reference like: `<Helmet {...helmetConfig.head} />`

og:site_name
og:type
og:locale
og:url
og:title
og:description
twitter:card
twitter:site 
twitter:creator
og:image
og:image:alt
og:image:type
og:image:width
og:image:height

Reference:  
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html
http://ogp.me/
https://developers.facebook.com/tools/debug/

**Comment by jlengstorf** [comment]
Good call, @mikelax! I've opened #141 to track this work.

**Pull request merged**
