### PR TITLE
fix: a11y links do not have discernible names

### PR DESCRIPTION
**Pull request by abhishekakade**
Fixes product links accessibility issues in accessibility audits (links do not have a discernible name).

### CODE REVIEW

**Comment by jlengstorf** [comment]
hey, @abhishekakade — I'm no longer with Gatsby, so I don't manage this repo anymore

thanks for submitting this, though! seems like a great addition

@gatsbyjs/core might be worth changing the code owners for this repo so it stops suggesting me as a reviewer?

**Comment by abhishekakade** [comment]
@jlengstorf, oh, I'm sorry, I didn't know that. And thanks! I'll wait for the team to review it.

**Comment by m-allanson** [comment]
@jlengstorf, I've opened https://github.com/gatsbyjs/store.gatsbyjs.org/pull/320 to try and prevent you from getting marked as a reviewer on PRs here.

@abhishekakade thank you! This looks like an improvement to me. However, I wonder if the description should be something like this? 

```
{`Product listing for ${title}`}
```

So that it describes the content of the target page. cc @madalynrose in case you have thoughts on this?

**Comment by abhishekakade** [comment]
> {`Product listing for ${title}`}

Yes, it does seem to describe the content in a better way. @m-allanson, @madalynrose, let me know if I can go ahead with this change or suggest improvements if any. Thank you!

**Comment by Developerayo** [comment]
> @jlengstorf, I've opened #320 to try and prevent you from getting marked as a reviewer on PRs here.
> 
> @abhishekakade thank you! This looks like an improvement to me. However, I wonder if the description should be something like this?
> 
> ```
> {`Product listing for ${title}`}
> ```
> 
> So that it describes the content of the target page. cc @madalynrose in case you have thoughts on this?

@m-allanson I believe having it described the title of the targeted page there would be a good change.

**Comment by abhishekakade** [comment]
Any update on this? @m-allanson

**Comment by pvdz** [comment]
Assigning to @madalynrose who's like the perfect one to review this, anyways :D

**Comment by madalynrose** [comment]
Oh goodness @abhishekakade I'm so sorry I haven't gotten to this!

Thank you so much for taking the time to improve accessibility in our store! This looks great!

**Comment by abhishekakade** [comment]
@madalynrose, thank you!

**Pull request merged**
