### PR TITLE
add pre-commit hook to run prettier

### PR DESCRIPTION
**Pull request by notdrone**

### CODE REVIEW

**Comment by jlengstorf** [comment]
Hi, @notdrone! Thanks for sending this in!

I just tried this locally, and the workflow is kind of confusing. What I was expecting was something like this:

1. I make a change to the code that violates Prettier rules
2. I add that code via `git add`
3. I commit the code (e.g. `git commit -m 'fix: change thing'`)
4. The pre-commit hook would fix and re-add the formatted code _before_ committing, **or** it would create a second commit (e.g. `git commit -m 'style: correct formatting issues'`)

Currently, the original, poorly formatted commit is created, and the style changes are staged — this seems like it will cause confusion and will likely lead to style fixes being missed (e.g. I run `git commit -am 'fix: thing'` and then `git push` without checking for newly staged changes).

Additionally, I think we're standardizing around [`lint-staged`](https://github.com/okonet/lint-staged) for this kind of work. @DSchau can you confirm that?

Looking at `lint-staged`, it looks like we could add either a `git commit -m 'style: fix formatting issues'` or a `git commit --amend` to make sure the formatting fixes actually end up being pushed.

Does this all make sense?

I'll wait for @DSchau to confirm, but I think what we'd want to do with this is:

1. Switch to `lint-staged`
2. Make sure style fixes do one of the following:
	- Fail the commit (probably not desirable)
	- Append the style fixes to the original commit (this is what I would prefer, but it also could be confusing if the committed code looks different from what was written)
	- Create a second `style:` commit (this is probably the least confusing option and would allow for rollbacks if necessary

Thanks!

**Comment by DSchau** [comment]
@jlengstorf yep, correct!

Generally, the approach I would recommend is something like the following:

- Swap `pretty-quick` with `lint-staged` (now that it has staged files support)
- Add a custom error handler (like in https://github.com/gatsbyjs/gatsby/blob/master/package.json#L58) that makes it clear when something has gone wrong how to avoid/fix

I'd recommend checking out our [existing config in Gatsby](https://github.com/gatsbyjs/gatsby/blob/master/package.json#L46-L60) for more info, here.

Tying into something like the above will hit that sweet spot that Jason mentions, namely that stylistic issues are fixed _as_ the commit happens, so stylistic concerns can be totally avoided come PR time.

Hope this helps--and please feel free to reach out if I can help further!

**Comment by jlengstorf** [comment]
We have this setup for the Gatsby core repo that I'd prefer to use: https://github.com/gatsbyjs/gatsby/blob/7fee09611b483e1bd1de03af3df5bac3dc8f464c/package.json#L46-L60

Note the call to `scripts/on-lint-error.js`, which logs information about how to solve linting errors. https://github.com/gatsbyjs/gatsby/blob/master/scripts/on-lint-error.js

For the store, this error message should read:

> Gatsby uses precommit hooks to run our linting and style checks. We do this to avoid additional hassle during pull request reviews. Please fix any linting problems before submitting pull request — all PRs must pass these checks before they can be merged.
>
> If you're doing something temporary, you can disable this hook with:
>
>     git commit --no-verify
>
> If you want disable this hook for all future commits:
>
>     npm run hooks:uninstall

**Comment by jlengstorf** [comment]
We just merged in #270, which is probably good enough for now. If someone wants to pick this up in a new PR, we'd be happy to see it!

**Pull request closed without merging**
